apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: null
  name: fortio
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      containerapp.apps.tanzu.vmware.com/app-name: fortio
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
