apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: fortio
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    containerapp.apps.tanzu.vmware.com/app-name: fortio
  type: ClusterIP
status:
  loadBalancer: {}
