#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"apiVersion": "apps/v1", "kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "workload"})
      - 
        #@overlay/match missing_ok=True
        args:
        - "server"
        - "-config-dir"
        - "/etc/fortio"

